packages:
  - packages/*
  - third-party/common/ts

blockExoticSubdeps: true

catalog:
  '@aws-sdk/client-dynamodb': 3.1024.0
  '@aws-sdk/client-lambda': 3.1024.0
  '@aws-sdk/client-ssm': 3.1024.0
  '@aws-sdk/lib-dynamodb': 3.1024.0
  '@eslint/js': 10.0.1
  '@lightweight-clients/jikan-api-lightweight-client': 4.0.2
  '@types/aws-lambda': 8.10.161
  '@types/node': 25.5.2
  '@vitest/coverage-v8': 4.1.4
  '@vitest/ui': 4.1.4
  aws-cdk: 2.1117.0
  aws-cdk-lib: 2.248.0
  aws-sdk-client-mock: 4.1.0
  cdk-lambda-llrt: 0.1.4
  constructs: 10.6.0
  cross-env: 10.1.0
  eslint: 10.2.0
  eslint-plugin-simple-import-sort: 12.1.1
  jiti: 2.6.1
  knip: 6.3.0
  msw: 2.13.0
  npm-run-all2: 8.0.4
  typescript: 6.0.2
  typescript-eslint: 8.58.1
  vitest: 4.1.4

minimumReleaseAge: 1400 # 1 day

nodeLinker: hoisted

onlyBuiltDependencies:
  - aws-sdk
  - esbuild
  - msw

trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@5.7.2"
