name: Shared Prerelease Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  prerelease-checks:
    name: Prerelease Checks
    runs-on: ubuntu-latest
    timeout-minutes: 2
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest@sha256:d89f8fcc6b1a39cb35976c248ed42a28c66ae00dc043099210f5571e42648ab4
        ports:
          - 8001:8000

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'true'

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Perform prerelease checks
        run: pnpm run prerelease
